### ISSUE TITLE
Line 171 Tournament.cs

### ISSUE THREAD

**Issue by AkaSoftBanana** [b2developer/MonopolyNEAT#5]
![image](https://user-images.githubusercontent.com/98223343/150651360-e99e60fe-e946-4509-af25-32e56b64e617.png)

Getting this issue with line 171 not sure why?

**Comment by AkaSoftBanana** [comment]
System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=Index was out of range. Must be non-negative and less than the size of the collection. Arg_ParamName_Name
  Source=System.Private.CoreLib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Monopoly.Tournament.PlayGameThread(Tournament instance, Int32 i) in D:\_Morgan\Personal\Programming\MonopolyNEAT-main\Monopoly\Tournament.cs:line 171
   at Monopoly.Tournament.<>c__DisplayClass11_0.<ExecuteTournamentRound>b__0() in D:\_Morgan\Personal\Programming\MonopolyNEAT-main\Monopoly\Tournament.cs:line 108
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

  This exception was originally thrown at this call stack:
    [External Code]
    Monopoly.Tournament.PlayGameThread(Monopoly.Tournament, int) in Tournament.cs
    Monopoly.Tournament.ExecuteTournamentRound.AnonymousMethod__0() in Tournament.cs
    [External Code]
